(require 'languages/cc)
(require 'languages/haskell)
(require 'languages/just)
(require 'languages/latex)
(require 'languages/nix)
(require 'languages/org)
(require 'languages/python)
(require 'languages/lean4)

(provide 'languages)
